name: build and release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: make gradlew executable
        run: chmod +x gradlew

      - name: build with gradle
        run: ./gradlew build

      - name: publish to github
        uses: Kira-NT/mc-publish@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Finds the jars in the build folders for both fabric and neoforge
          files: |
            fabric/build/libs/farsightedmobs-fabric-*.jar
            neoforge/build/libs/farsightedmobs-neoforge-*.jar
